import { routes } from "./routes";

const routes_names = [
  { path: routes.LOANDASHBOARDHOME, name: "Loan Dashboard" },
  { path: routes.LOANFILTER, name: "Filter/Search Loans" },
  { path: routes.LOANPOLICY, name: "Loan Policy" },
  { path: routes.LOANOFFER, name: "Loan Offer" },
  { path: routes.LOANAPPLY, name: "Loan Application" },
  { path: routes.LOANVERIFICATION, name: "Loan Verification" },
  { path: routes.LOANAPPROVED, name: "Loan Approved" },
  { path: routes.LOANDECLINED, name: "Loan Declined" },
  { path: routes.LOANACCOUNTS, name: "My Accounts" },
  { path: routes.LOANACCOUNTSNEW, name: "New Loan Account" },
  { path: routes.LOANHISTORY, name: "Loan History" },
  { path: routes.LOANPAYBACK, name: "Payback Loan" },
  { path: routes.RECRUITMENTDASHBOARD, name: "Recruitment Dashboard" },
  { path: routes.RECRUITMENT_WORK_EXPERIENCE, name: "Add Work Experience" },
  { path: routes.RECRUITMENTRESUME_FOREIGN, name: "Foreign Resume" },
  { path: routes.RECRUITMENT_EMPLOYER, name: "Employer | Post Jobs" },
  { path: routes.RECRUITMENT_JOBS, name: "All Jobs" },
  { path: routes.RECRUITMENT_COVER_LETTER, name: "Cover Letter" },
  { path: routes.RECRUITMENT_REF, name: "Provide Reference" },
  { path: routes.RECRUITMENT_CONTACT, name: "Contact Information" },
  { path: routes.RECRUITMENT_OTHERS, name: "Other Information" },
  { path: routes.RECRUITMENT_PROFILE_PICTURE, name: "Profile Picture" },
  { path: routes.RECRUITMENT_CV, name: "Curriculum Vitae" },
  { path: routes.RECRUITMENT_PREVIEW_RESUME, name: "Preview Resume" },
  { path: routes.RECRUITMENTRESUME, name: "Resume" },
  { path: routes.RECRUITMENT_FOREIGN_EDUCATION, name: " Education" },
  {
    path: routes.RECRUITMENT_FOREIGN_WORK_EXPERIENCE,
    name: " Work Experience",
  },
  { path: routes.RECRUITMENT_FOREIGN_COVER_LETTER, name: " Cover Letter" },
  { path: routes.RECRUITMENT_FOREIGN_REF, name: " Reference" },
  { path: routes.RECRUITMENT_FOREIG_CONTACT, name: " Contact" },
  { path: routes.RECRUITMENT_FOREIGN_OTHERS, name: " Other Information" },
  {
    path: routes.RECRUITMENT_FOREIGN_PROFILE_PICTURE,
    name: " Profile Picture",
  },
  { path: routes.RECRUITMENT_FOREIGN_CV, name: " CV" },
  { path: routes.RECRUITMENT_PREVIEW_FOREIGN_RESUME, name: "Preview Resume" },
  { path: routes.RECRUITMENT_FOREIGN_RESUME, name: " Resume" },
  { path: routes.RECRUITMENT_FOREIGN_BIO, name: "Bio" },

  { path: routes.TELEMEDICINE_DASHBOARD, name: "Telemedicine Dashboard" },
  { path: routes.TELEMEDICINE_PRACTITIONERS, name: "Practitioners" },
  { path: routes.TELEMEDICINE_APPOINTMENTS, name: "Appointments" },
  { path: routes.TELEMEDICINE_FAQ, name: "FAQ" },
  { path: routes.TELEMEDICINE_TERMS, name: "Terms" },
  { path: routes.TELEMEDICINE_PROFILE, name: "Profile" },
  { path: routes.TELEMEDICINE_CONTACT, name: "Contact" },
  { path: routes.TELEMEDICINE_SPECIALISTS, name: "Specialists" },
  {
    path: routes.TELEMEDICINE_PRACTITIONERS_REVIEWS,
    name: "Practitioners Reviews",
  },
  {
    path: routes.TELEMEDICINE_PRACTITIONERS_FAVORITES,
    name: "Favorites Doctors",
  },
    {
    path: routes.TELEMEDICINE_ORGANIZATION,
    name: "Organizations",
  },
];

export default routes_names;
